# Generated by Django 4.2.7 on 2024-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_movement_personaldetail_delete_member_delete_member1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='lastname',
        ),
    ]
