# Generated by Django 4.2.7 on 2024-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_remove_movement_firstname_remove_movement_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
